name: "Uptonight"
description: "Uptonight homeassistant addon"
version: "0.0.1"
slug: "uptonight"
init: false
arch:
  - amd64
  - i386
options:
  location:

    LATITUDE: "0"
    LONGITUDE: "0"
schema:
  location:
    LATITUDE: str
    LONGITUDE: str
startup: system
timeout: 300
