name: "Uptonight"
description: "Uptonight homeassistant addon"
version: "0.0.1"
slug: "uptonight"
init: false
arch:
  - amd64
  - i386
options:
  location:
    latitude: "0"
    longitude: "0"
  output_dir: ../data

schema:
  output_dir: str
  location:
    latitude: str
    longitude: str
startup: system
timeout: 300
